version: '3.8'

services:
  mongo1:
    image: mongo:4
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    volumes:
      - /mongodata/mongo1:/data/db
    networks:
      - mongoCluster
    ports:
      - "27017:27017"

  mongo2:
    image: mongo:4
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    volumes:
      - /mongodata/mongo2:/data/db
    networks:
      - mongoCluster
    ports:
      - "27018:27017"

  mongo3:
    image: mongo:4
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    volumes:
      - /mongodata/mongo3:/data/db
    networks:
      - mongoCluster
    ports:
      - "27019:27017"

  yolo5_service:
    image: asyas/yolo5_image
    environment:
      BUCKET_NAME: asya-bucket
    volumes:
      - $HOME/.aws:/root/.aws
    networks:
      - mongoCluster
    ports:
      - "8081:8081"
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  polybot_service:
    image: asyas/polybot_image
    environment:
      BUCKET_NAME: asya-bucket
      YOLO5_URL: http://yolo5_service:8081/predict
    volumes:
      - $HOME/.aws:/root/.aws
    networks:
      - mongoCluster
    ports:
      - "8443:8443"
    depends_on:
      - yolo5_service

networks:
  mongoCluster:
    driver: bridge
